# Generated by Django 5.0.14 on 2026-07-09 10:18

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=16, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
